// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Server.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20220812121337_InitialData")]
    partial class InitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Entities.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Organizer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6cead492-73c4-48cf-9d77-4c3ef35052cb"),
                            Description = "Excursion to the Museum of old cars",
                            Name = "Excursion",
                            Organizer = "Nikita Kislov",
                            Place = "L.Sapegi 5",
                            Time = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2195fd5f-7453-47d1-9387-3a45042c68a1"),
                            Description = "Сinema evening of scary movies",
                            Name = "Movie Night",
                            Organizer = "Ivan Filimonov",
                            Place = "R.Slovat 44",
                            Time = new DateTime(2022, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("568b22ff-d7a2-4e8e-8291-e70219781699"),
                            Description = "Birthday of Nick, 25 years",
                            Name = "Birthday",
                            Organizer = "Andrey Ivanov",
                            Place = "O.Rydnova 32",
                            Time = new DateTime(2022, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1bdbc616-2a86-4a08-a804-bb8fddc1b6ee"),
                            Description = "Fitness training for beginners",
                            Name = "Fitness Training",
                            Organizer = "Alex Ivanov",
                            Place = "Pavlov Park",
                            Time = new DateTime(2022, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
